# Generated by Django 4.1.3 on 2022-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Прізвище Ім'я")),
                ('registrations', models.IntegerField(default=0, null=0, verbose_name="Прізвище Ім'я")),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_patient', models.CharField(default='-', max_length=255, null='-', verbose_name="Ім'я пацієнта")),
                ('name_of_doctor', models.CharField(default='-', max_length=255, null='-', verbose_name="Ім'я лікаря")),
                ('name_of_procedure', models.CharField(max_length=255, verbose_name='Назва процедури')),
                ('day', models.IntegerField(default=0, null=0, verbose_name='День')),
                ('hour', models.IntegerField(verbose_name='Година')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_number', models.IntegerField(verbose_name='Номер кабінету')),
                ('name_of_doctor', models.CharField(default='-', max_length=255, null='-', verbose_name="Ім'я лікаря")),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Прізвище Ім'я")),
                ('registrations', models.IntegerField(default=0, null=0, verbose_name="Прізвище Ім'я")),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва процедури')),
                ('name_of_speciality', models.CharField(default='-', max_length=255, null='-', verbose_name="Ім'я лікаря")),
                ('duration', models.IntegerField(verbose_name='Тривалість')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Прізвище Ім'я")),
                ('location', models.CharField(default='-', max_length=255, null='-', verbose_name='Місце роботи')),
                ('speciality', models.CharField(max_length=20, verbose_name='Спеціальність')),
                ('schedule_from', models.CharField(max_length=30, verbose_name='Розклад від')),
                ('schedule_to', models.CharField(max_length=30, verbose_name='Розклад до')),
            ],
        ),
    ]
